create table author
(
    id bigint generated by default as identity
        constraint author_pkey
            primary key,
    name varchar(255) not null
        constraint uk_or6k6jmywerxbme223c988bmg
            unique
);

alter table author owner to postgres;

create table book
(
    id bigint generated by default as identity
        constraint book_pkey
            primary key,
    description varchar(4096),
    quantity integer not null
        constraint book_quantity_check
            check (quantity >= 0),
    title varchar(255) not null
        constraint uk_g0286ag1dlt4473st1ugemd0m
            unique
);

alter table book owner to postgres;

create table author_book
(
    author_id bigint not null
        constraint fkg7j6ud9d32ll232o9mgo90s57
            references author,
    book_id bigint not null
        constraint fkn8665s8lv781v4eojs8jo3jao
            references book,
    constraint author_book_pkey
        primary key (author_id, book_id)
);

alter table author_book owner to postgres;

create table customer
(
    id bigint generated by default as identity
        constraint customer_pkey
            primary key,
    email varchar(255)
        constraint uk_dwk6cx0afu8bs9o4t536v1j5v
            unique,
    first_name varchar(255),
    last_name varchar(255),
    login varchar(255)
        constraint uk_l4t3rudi0h7ibnjpnbvcnkcbf
            unique
);

alter table customer owner to postgres;

create table borrowed
(
    id bigint generated by default as identity
        constraint borrowed_pkey
            primary key,
    borrow_date date,
    return_date date,
    return_till_date date,
    book_id bigint
        constraint fk12f5gislq2tllernptxtq6mmx
            references book,
    customer_id bigint
        constraint fk2yi7s31f60y81bnr5cp6ysr5j
            references customer
);

alter table borrowed owner to postgres;

