create table author
(
    id bigint generated by default as identity
        constraint author_pkey
            primary key,
    name varchar(255) not null
        constraint uk_or6k6jmywerxbme223c988bmg
            unique
);

alter table author owner to postgres;

create table book
(
    id bigint generated by default as identity
        constraint book_pkey
            primary key,
    description varchar(4096),
    title varchar(255) not null
        constraint uk_g0286ag1dlt4473st1ugemd0m
            unique
);

alter table book owner to postgres;

create table author_book
(
    author_id bigint not null
        constraint fkg7j6ud9d32ll232o9mgo90s57
            references author,
    book_id bigint not null
        constraint fkn8665s8lv781v4eojs8jo3jao
            references book,
    constraint author_book_pkey
        primary key (author_id, book_id)
);

alter table author_book owner to postgres;

create table usr
(
    id bigint generated by default as identity
        constraint usr_pkey
            primary key,
    email varchar(255)
        constraint uk_g9l96r670qkidthshajdtxrqf
            unique,
    first_name varchar(255),
    last_name varchar(255),
    login varchar(255)
        constraint uk_b2j2bjirhqhbg1rsexaq5qs9x
            unique,
    password varchar(255),
    user_role varchar(255)
);

alter table usr owner to postgres;

